### ISSUE TITLE
cadastrapp : impossible de switcher sur un tag

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra_documentation#5]
Ubuntu Desktop 20.04 avec Python 3.9.9

Lorsque je lance le `build.bash` j'ai cette erreur qui remonte et du coup ça builde que la doc sur master.

```bash
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 build de : Cadastrapp-V2.0
HEAD est maintenant sur abc6ea5 [maven-release-plugin] prepare release Cadastrapp-v2.0
Sphinx v4.4.0 en cours d'exécution

Configuration error:
Votre fichier de configuration comporte une erreur de programmation : 

Traceback (most recent call last):
  File "/home/mael/georchestra_documentation/.venv/lib/python3.9/site-packages/sphinx/config.py", line 340, in eval_config_file
    exec(code, namespace)
  File "/home/mael/georchestra_documentation/cadastrapp/repo/docs/conf.py", line 124, in <module>
    current_version = repo.active_branch.name
  File "/home/mael/georchestra_documentation/.venv/lib/python3.9/site-packages/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "/home/mael/georchestra_documentation/.venv/lib/python3.9/site-packages/git/refs/symbolic.py", line 294, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'abc6ea5e196493c0c819627d2c6c86431c15f241'
```

J'arrive pas trop à comprendre ce qui ne va pas.  Quelqu'un pour reproduire ?

**Comment by MaelREBOUX** [comment]
fermeture cause passage à mkdocs
